### ISSUE TITLE
Hello, I am very interested in your research, but I have encountered some mistakes, how should I solve them？Thanks!

### ISSUE THREAD

**Issue by song201216** [zengxianyu/crfill#17]
Traceback (most recent call last):
File "E:\code\crfill-master\train.py", line 14, in
opt = TrainOptions().parse()
File "E:\code\crfill-master\options\base_options.py", line 151, in parse
opt = self.gather_options()
File "E:\code\crfill-master\options\base_options.py", line 76, in gather_options
model_option_setter = models.get_option_setter(model_name)
File "E:\code\crfill-master\models_init_.py", line 35, in get_option_setter
model_class = find_model_using_name(model_name)
File "E:\code\crfill-master\models_init_.py", line 15, in find_model_using_name
modellib = importlib.import_module(model_filename)
File "D:\software\Anaconda3\envs\sss\lib\importlib_init_.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1030, in _gcd_import
File "", line 1007, in _find_and_load
File "", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.pix2pix_model'
If you can help me take care of him, I will be very grateful to you!

**Comment by wangxinzhe0617** [comment]
> Traceback (most recent call last): File "E:\code\crfill-master\train.py", line 14, in opt = TrainOptions().parse() File "E:\code\crfill-master\options\base_options.py", line 151, in parse opt = self.gather_options() File "E:\code\crfill-master\options\base_options.py", line 76, in gather_options model_option_setter = models.get_option_setter(model_name) File "E:\code\crfill-master\models_init_.py", line 35, in get_option_setter model_class = find_model_using_name(model_name) File "E:\code\crfill-master\models_init_.py", line 15, in find_model_using_name modellib = importlib.import_module(model_filename) File "D:\software\Anaconda3\envs\sss\lib\importlib_init_.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 984, in _find_and_load_unlocked ModuleNotFoundError: No module named 'models.pix2pix_model' If you can help me take care of him, I will be very grateful to you!

do you run
git submodule init
git submodule update

**Comment by RahulBhalley** [comment]
I have same error. No `models.pix2pix_model` found.

**Comment by zengxianyu** [comment]
what's the command you use to run this code? you should always follow the .sh script I provided

**Comment by zengxianyu** [comment]
what's the command you use to run this code?
