### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'load_baseg'

### ISSUE THREAD

**Issue by zborger** [zengxianyu/crfill#31]
Traceback (most recent call last):
  File "/root/crfill/train.py", line 27, in <module>
    trainer = create_trainer(opt)
  File "/root/crfill/trainers/__init__.py", line 25, in create_trainer
    instance = model(opt)
  File "/root/crfill/trainers/pix2pix_trainer.py", line 20, in __init__
    self.pix2pix_model = models.create_model(opt)
  File "/root/crfill/models/__init__.py", line 41, in create_model
    instance = model(opt)
  File "/root/crfill/models/inpaint_model.py", line 32, in __init__
    self.netG, self.netD = self.initialize_networks(opt)
  File "/root/crfill/models/inpaint_model.py", line 110, in initialize_networks
    netG = util.load_network(netG, 'G', opt.which_epoch, opt)
  File "/root/crfill/util/util.py", line 222, in load_network
    if opt.load_baseg:
AttributeError: 'Namespace' object has no attribute 'load_baseg'

在python train.py 的第二和第三阶段我都遇到了这个问题，请问该如何解决呢，期待您的回复

**Comment by wangchangquan** [comment]
i encounter the same , have solve the problem?

**Comment by jadidimohammad** [comment]
> i encounter the same , have solve the problem?

Hi could you solve it?

**Comment by jadidimohammad** [comment]
> Traceback (most recent call last): File "/root/crfill/train.py", line 27, in trainer = create_trainer(opt) File "/root/crfill/trainers/**init**.py", line 25, in create_trainer instance = model(opt) File "/root/crfill/trainers/pix2pix_trainer.py", line 20, in **init** self.pix2pix_model = models.create_model(opt) File "/root/crfill/models/**init**.py", line 41, in create_model instance = model(opt) File "/root/crfill/models/inpaint_model.py", line 32, in **init** self.netG, self.netD = self.initialize_networks(opt) File "/root/crfill/models/inpaint_model.py", line 110, in initialize_networks netG = util.load_network(netG, 'G', opt.which_epoch, opt) File "/root/crfill/util/util.py", line 222, in load_network if opt.load_baseg: AttributeError: 'Namespace' object has no attribute 'load_baseg'
> 
> 在python train.py 的第二和第三阶段我都遇到了这个问题，请问该如何解决呢，期待您的回复

could you solve it?
